### ISSUE TITLE
Make a CRAN release

### ISSUE THREAD

**Issue by mailund** [Konrad1991/dfdr#6]
Clean up the code a little and test it, and then make a release.

**Comment by mailund** [comment]
Hmm, I'm not entirely sure. The last two times I put something on CRAN was a hassle and not exactly a pleasant experience, so I sort of stopped. But if it is something you need, I am happy to give it a go.

**Comment by Konrad1991** [comment]
I'm really interested to use it. I think I will best explain it in the other issue.... ;)

**Comment by mailund** [comment]
I quickly scanned the other issue, but I have to run now to deal with some things, so I think I will have to wait until Monday to answer. Sorry. Busy day today. But the ODE application looks really interested!

**Comment by Konrad1991** [comment]
No problem. Looking forward to hear from you
